# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Church.IO
email: info@church.io
description: > # this means to ignore newlines until "baseurl:"
    The website of Church.IO, an organization creating and promoting open source church software.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://church.io" # the base hostname & protocol for your site
twitter_username: churchio
github_username:  churchio

# Build settings
markdown: kramdown

# Bootstrap include
sass:
  style: compressed
